//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab26x.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID { get; set; }
        public string Coffee_Mug { get; set; }
        public string Coffee_Tumbler { get; set; }
        public string Coffee_Shop_Shirt { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
        public string Item1 { get; set; }
    }
}
